### PR TITLE
Update to 0.17.52

### PR DESCRIPTION
**Pull request by carlbennett**
https://www.reddit.com/r/factorio/comments/c4qf6n/version_01752/

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
@Fank Is the updater down or was it not fast enough?

**Comment by Fank** [comment]
I locked my self out of my server .... and due to the repo move its messed up.
Ill try to fix it the next days, i need to find my old ssh keys again ....

**Comment by bplein** [comment]
Should we open an issue to track this until automated updates are back online?

**Comment by SuperSandro2000** [comment]
@bplein I try to set up his script this evening. If I don't finish it we should open up an issue.

**Comment by bplein** [comment]
@SuperSandro2000 ... cool, sure beats building my own and changing my docker-compose files etc. just to keep the servers up to date (grin).

If the scripts are sharable I'd love to learn from them. But I understand that not everyone wants to share private scripting. If they did, they'd put it on github :)

**Comment by SuperSandro2000** [comment]
My bot just pushed this https://github.com/factoriotools/factorio-docker/commit/5b24f8ac74311414fd03a4bd97da51dc847816a9 .

I did the user different on purpose to not credit me to much contribution.

@bplein I actually share most of my scripts that are not to niche on github and the watchdog is listed here https://github.com/factoriotools/factorio-docker-watchdog . I plan to maintain for now.

**Pull request merged**
