### PR TITLE
Updated update.sh and clear data from broken github action!

### PR DESCRIPTION
**Pull request by MrBasicX**

### CODE REVIEW

**Comment by jonojr** [comment]
I'm just going to check this out and make sure it works

**Comment by LsHallo** [comment]
Same thing for me: `yq: -i/--in-place can only be used with -y/-Y`

**Comment by miragecentury** [comment]
Result for `buildinfo.json` from a quick test.
`  },
  "2.0.7": {
    "sha256": "e6a64a9ee5b1d3773cd1f40aa5cf78e91960eade6c508fd365c34752afdf2762",
    "tags": [
      "latest",
      "stable",
      "stable-2.0.7",
      "2",
      "2.0",
      "2.0.7"
    ]
  }`

**Comment by miragecentury** [comment]
> yq: -i/--in-place can only be used with -y/-Y

For me, it's a yq version mismatch. ( Not a behavior to be expected in the action run ).

**Comment by jonojr** [comment]
> Same thing for me: `yq: -i/--in-place can only be used with -y/-Y`

I get the same, but the lines using it have not been changed, and we get past the issue with getting the checksum.
I am betting this is a version mismatch for yq, so I think we are fine

**Comment by LsHallo** [comment]
> > Same thing for me: `yq: -i/--in-place can only be used with -y/-Y`
> 
> I get the same, but the lines using it have not been changed, and we get past the issue with getting the checksum. I am betting this is a version mismatch for yq, so I think we are fine



> > yq: -i/--in-place can only be used with -y/-Y
> 
> For me, it's a yq version mismatch. ( Not a behavior to be expected in the action run ).

Yeah thinking the same. LGTM

**Comment by MelaineGerard** [comment]
I can confirm the result of the buildinfo.json

**Pull request merged**
