### PR TITLE
Update to 0.17.54

### PR DESCRIPTION
**Pull request by carlbennett**
https://www.reddit.com/r/factorio/comments/c928b4/version_01754/

### CODE REVIEW

**Comment by carlbennett** [comment]
This will require #270 to be merged before the image will not cause errors when trying to run.

**Comment by SuperSandro2000** [comment]
@Fank can we please wait on manually updates so that I can get the watchdog working properly? I don't want to update every version manually and if we merge this I can't debug the watchdog easily.

**Comment by SuperSandro2000** [comment]
I should have the watchdog working again. Let us see if it works for 0.17.55.

**Comment by Fank** [comment]
@SuperSandro2000 ok

**Pull request merged**
