### PR TITLE
Build in reverse order of versions

### PR DESCRIPTION
**Pull request by rissson**
Sort versions in buildinfo.json before building and always build newer versions first.

### CODE REVIEW

**Comment by miragecentury** [comment]
I was thinking of proposing the same.
I understand why rebuilding everything to update packages is necessary. 
But yes, the first will is to have the latest asap.

**Comment by EternalDeiwos** [comment]
I am so glad I am not the only person staring at the build thinking this 😂 

I was also thinking there could be better layer between the container versions if the `apt` related stuff were in its own build step in the Dockerfile... but that's just nitpicking

**Comment by rissson** [comment]
> I am so glad I am not the only person staring at the build thinking this 😂
> 
> I was also thinking there could be better layer between the container versions if the `apt` related stuff were in its own build step in the Dockerfile... but that's just nitpicking

Agreed I was also thinking this. The thing to keep in mind is data that persists across layers only to be deleted later on. The build certainly could be improved w/o this issue, and it would also apply less pressure on the infrastructure serving packages.

But that will be for another PR

**Comment by Fank** [comment]
Thanks that keeps the most important at the top. 👍

**Pull request merged**
