### PR TITLE
Update scenario.sh

### PR DESCRIPTION
**Pull request by xxalfa**
In case this file "server-settings.template.json" with the following content exists, it will be applied to the server-settings.json.

"name": "${INSTANCE_NAME}", 
"description": "${INSTANCE_DESC}",

The following is deposited when using "docker run".

--env "INSTANCE_NAME=Your Instance's Name", 
--env "INSTANCE_DESC=Your Instance's Description",

### CODE REVIEW

**Comment by xxalfa** [comment]
In a local test, the conversion of the variables works. Unfortunately, a test with my own image failed. The env variables are not taken over, does anyone have any idea what the error might be?

**Comment by xxalfa** [comment]
With my last change, it should work.

**Comment by SuperSandro2000** [comment]
I don't like the approach of this PR. I would support a solution where you would set the environment variables directly.

Also please test your PRs more and use a git client or the command line and not the GitHub web interface. This is quiet messy and could be avoided with force pushes also ``envsubst`` is not installed by default on alpine and I don't think we need to install it for that one use case.

**Comment by xxalfa** [comment]
Well I have used the web interface, because my changes should be unique and I wanted to delete the respository afterwards.  So I really do not like the behavior of envsubst either.  I will think of something.

**Comment by SuperSandro2000** [comment]
> Well I have used the web interface

You are severely limiting yourself by doing it.

> because my changes should be unique

You do the exact same changes in the cli.

Also ``envsubst`` is not available on alpine.

**Comment by xxalfa** [comment]
I had the hope to find a different solution, the problem is, the command `/config set name new_server_name` only works if you run it as a player in the game. 

```
if [[ -f "$CONFIG/server-settings.json" ]] && [[ -n "${INSTANCE_NAME}" ]] && [[ -n "${INSTANCE_DESC}" ]]; then
  sed --in-place "s/__INSTANCE_NAME__/${INSTANCE_NAME}/g;s/__INSTANCE_DESC__/${INSTANCE_DESC}/g" "$CONFIG/server-settings.json"
fi
```

This is my latest solution, which has only the problem that the server-settings.json is read back. Is there a way to say that /opt/factorio should only be read?

**Comment by SuperSandro2000** [comment]
Just only check ``/opt/factorio``?

**Comment by xxalfa** [comment]
I have to correct my statement. As soon as "Factorio initialized" the command `/config set name INSTANCE_NAME \n` can be used via stdin.

If the container is closed, the scenario is saved automatically, this can cause problems with several containers, this is to prevent the following command. 
```bash
chattr +i /opt/factorio/saves/SCENARIO.zip
chattr +i /opt/factorio/saves/SCENARIO.tmp.zip
```

**Pull request closed without merging**
