### PR TITLE
Update to Factorio 0.18.0 and 0.18.1

### PR DESCRIPTION
**Pull request by MagicHack**
I'm not 100% sure if the travis.yml is updated correctly, I can change it if there's a problem

### CODE REVIEW

**Comment by Fank** [comment]
LGTM, i don't know the correct travis syntax either.
But i am going to merge it, but release 0.18.0 first and then tag 0.18.1 after it.

**Comment by SuperSandro2000** [comment]
https://travis-ci.org/factoriotools/factorio-docker/jobs/640742595 is red cause it is missing the credentials in pull requests.

**Comment by SuperSandro2000** [comment]
https://travis-ci.org/factoriotools/factorio-docker/jobs/640742595 is red cause it is missing the credentials in pull requests.

**Comment by SuperSandro2000** [comment]
> I'm not 100% sure if the travis.yml is updated correctly, I can change it if there's a problem

IIRC it is fine. ``STABLE`` needs to be set when 0.18 begins to get stable releases.

**Pull request merged**
