### PR TITLE
Factorio 1.1.38 update

### PR DESCRIPTION
**Pull request by jorisdrenth**

### CODE REVIEW

**Comment by nils-mueller** [comment]
@jorisdrenth I do not know, if somebody should be assigned as Reviewer to this PR.

**Comment by jorisdrenth** [comment]
@nils-mueller Neither do I, maybe @Fank or @SuperSandro2000 can tell us?

**Review by egyptianbman — APPROVED** [review]

**Comment by georgevanburgh** [comment]
Looks like this needs a tag in order to publish?

**Comment by Fank** [comment]
Yes its comming now

**Pull request merged**
